### ISSUE TITLE
`| into string` does not always work 

### ISSUE THREAD

**Issue by ActuallyHappening** [abusch/nu_plugin_semver#3]
IDK exactly why this triggers, but try running this code and for me it errors:
```nu
"1.2.3" | into semver | into string
```
Nu version 0.93.0
Error:
![image](https://github.com/abusch/nu_plugin_semver/assets/105958073/867e28d9-50c3-42f1-b385-ba9fa3721e21)
"command doesn't support semver input"

**Comment by abusch** [comment]
Ah, that's because it should be `| to text`. I'll update the README. And yes, it's confusing that there is both `to text` and `into string` and that they behave differently 😕

**Comment by ActuallyHappening** [comment]
Ah yes thank you, your project fills my need very well so this fix is greatly appreciated :)
